name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
    ci:
        runs-on: ubuntu-20.04
        container: lironavon/docker-puppeteer-container:14.16.0
        env:
          CI: true
        steps:
            # add git to the container and set it up with the token
            - name: setup git in container
              uses: actions/checkout@v2
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
            # cache the dependencies from any node_modules directory
            - name: cache dependencies
              uses: actions/cache@v2
              with:
                path: '**/node_modules'
                key: node_modules-${{ hashFiles('**/package-lock.json')}}
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test-web