name: Node.js CI

on:
  # pull_request:
  #   branches: [ master ]
  push:
    # branches: [ master ]
    paths:
      - 'ecmascript/**'
  workflow_dispatch:
  

jobs:
  test:
    runs-on: ubuntu-latest

    # strategy:
    #     matrix:
    #       node-version: [ 10.17.0, 17.9.0 ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        # with:
        #   node-version: ${{ matrix.node-version }}
      - run: cd ecmascript && npm install && npm run compile
      # - run: sed -i '/ecmascript\/lib\//d' .gitignore
      # - run: git config --global user.email "bot@echo-d.net && git config --global user.name "Bot"
      # - run: git add .gitignore ecmascript/lib && git commit -m "add ignored files for codecov"
      # - run: cat .gitignore
      - run: cd ecmascript && npm run test-cov
      # - run: npm ci
      # - run: npm run build --if-present
      # - run: npm test
      # - run: ls -l ecmascript/test/coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ecmascript/test/coverage
          # verbose: true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results
