name: Web CI

on:
  # pull_request:
  #   branches: [ main ]
  push:
    # branches: [ main ]
    paths:
      - 'ecmascript/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    container: lironavon/docker-puppeteer-container:14.16.0
    env:
      CI: true
    steps:
      # add git to the container and set it up with the token
      - name: setup git in container
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          # node-version: ${{ matrix.node-version }}
      # cache the dependencies from any node_modules directory
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/package-lock.json')}}
      - run: rm -rf ecmascript/test/report && rm -rf ecmascript/test/coverage
      - name: Install dependencies
        run: cd ecmascript && npm install
      - name: Build web bundle
        run: cd ecmascript && npm run build
      - name: Run tests
        run: cd ecmascript && npm run test-web