name: Bun CI

on:
  # pull_request:
  #   branches: [main]
  push:
    # branches: [main]
    paths:
      - 'ecmascript/**'
  # workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     deno-version: [ 1.0.11, 1.14.0 ]

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        # with:
        #   bun-version: ${{ matrix.deno-version }}

      - run: rm -rf ecmascript/test/report && rm -rf ecmascript/test/coverage
      - run: cd ecmascript && bun install
      - run: cd ecmascript && script/test/sys-bun.sh